//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATIONS
    {
        public APPLICATIONS()
        {
            this.RULES_APP = new HashSet<RULES_APP>();
        }
    
        public int app_id { get; set; }
        public string name { get; set; }
        public string apk_name { get; set; }
    
        public virtual ICollection<RULES_APP> RULES_APP { get; set; }
    }
}
