//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYOD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BYODEntities : DbContext
    {
        public BYODEntities()
            : base("name=BYODEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APPLICATIONS> APPLICATIONS { get; set; }
        public DbSet<DEVICES> DEVICES { get; set; }
        public DbSet<RECENT_LOCATION> RECENT_LOCATION { get; set; }
        public DbSet<RULES> RULES { get; set; }
        public DbSet<RULES_APP> RULES_APP { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<USERS> USERS { get; set; }
    }
}
