//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICES
    {
        public DEVICES()
        {
            this.RECENT_LOCATION = new HashSet<RECENT_LOCATION>();
        }
    
        public int device_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string name { get; set; }
        public Nullable<int> phone_number { get; set; }
        public string description { get; set; }
        public Nullable<bool> status { get; set; }
        public string model { get; set; }
        public string imei { get; set; }
        public string platform { get; set; }
        public Nullable<System.DateTime> last_login_time { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> date_stolen { get; set; }
        public Nullable<bool> isstolen { get; set; }
        public Nullable<bool> isremove { get; set; }
        public Nullable<System.DateTime> date_remove { get; set; }
        public Nullable<bool> iswipe { get; set; }
        public Nullable<System.DateTime> date_wipe { get; set; }
        public string reg_id { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual ICollection<RECENT_LOCATION> RECENT_LOCATION { get; set; }
    }
}
