//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RULES
    {
        public RULES()
        {
            this.RULES_APP = new HashSet<RULES_APP>();
            this.USERS = new HashSet<USERS>();
        }
    
        public int rules_id { get; set; }
        public string name { get; set; }
        public Nullable<bool> allow_copy_paste { get; set; }
        public Nullable<bool> allow_email { get; set; }
        public Nullable<bool> allow_camera { get; set; }
        public Nullable<bool> allow_microphone { get; set; }
        public Nullable<bool> allow_airplan_mode { get; set; }
        public Nullable<bool> allow_screen_capture { get; set; }
        public Nullable<bool> allow_clipboard { get; set; }
        public Nullable<bool> allow_home_key { get; set; }
        public Nullable<int> dowload_type { get; set; }
        public Nullable<bool> allow_share { get; set; }
    
        public virtual ICollection<RULES_APP> RULES_APP { get; set; }
        public virtual ICollection<USERS> USERS { get; set; }
    }
}
