//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RULES_APP
    {
        public int id { get; set; }
        public Nullable<int> rules_id { get; set; }
        public Nullable<int> app_id { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual APPLICATIONS APPLICATIONS { get; set; }
        public virtual RULES RULES { get; set; }
    }
}
