//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace BYOD.Models
{
    
    public partial class USERS
    {
        public USERS()
        {
            this.DEVICES = new HashSet<DEVICES>();
        }
    
        public int user_id { get; set; }


        [Required]
        [Remote("check_user", "Users", HttpMethod = "POST", ErrorMessage = "User name already exists. Please enter a different user name.")]
        public string username { get; set; }

        [Required]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        [StringLength(50, MinimumLength = 3)]
        public string name { get; set; }

        [Required]
        [EmailAddress]
        [Remote("check_email", "Users", HttpMethod = "POST", ErrorMessage = "Email already exists. Please enter a different email.")]
        public string email { get; set; }

        [Required]
        public string password { get; set; }

        public Nullable<int> rules_id { get; set; }

        public virtual ICollection<DEVICES> DEVICES { get; set; }
        public virtual RULES RULES { get; set; }
    }
}
